### ISSUE TITLE
Stuck after a failed planet selection

### ISSUE THREAD

**Issue by puggan** [st0x0ef/stellaris#170]
Playing the modpack Techopolis 3-9.0, including Stellaris 1.2.7.

After taking my first rocket to space, and reaching the planet selection, i open the quest-book to verify where I was going.
I was going to the moon, but after closing the quest-book I could no longer select a destination.

While clicking to see if something could trigger the selector, I exited the rocket :-(

<img width="2814" height="1729" alt="Image" src="https://github.com/user-attachments/assets/2f1bd854-148c-47fd-b5dc-2eaa8c8ffa7c" />

As a way to try to solve it, I used /home to re-try.
At home I have no height control, but I succeed in putting down a 2nd rocket, fueling it, and off I went a 2nd time.

But this time after reaching space, the destination selector didn't appear, it just continue higher and higher.
(rocket icon is almost at the top of the screen in the screenshoot)

<img width="2814" height="1729" alt="Image" src="https://github.com/user-attachments/assets/ab27dbca-ea91-4318-acdb-7f8e841556bd" />

Don't know if it's a bug in the mod, or just a problem in the mod pack, but I wanted to inform you atleast.

**Comment by st0x0ef** [comment]
The latest update of the mod is 1.4.13, this bug as probably been fixed in a while now. Please make sure you use the latest version before posting an issue.

**Comment by puggan** [comment]
The 1.2.7 is the latest in the 1.2.x serie?, The changelog is a bit hard to read as you seams to wipe it with each version.
Updateing to 1.3 or 1.4 have a high risk of breaking the mod-pack.
Just going to load the latest backup and try again.

**Comment by st0x0ef** [comment]
You can update to the latest version without breaking your modpack. There's no break change between those version.

**Comment by muggleorwizard** [comment]
I can confirm that this is still an issue for some players on the latest version - [Neoforge 1.21] Stellaris 1.4.22
NeoForge 1.21.1
When in a rocket that is taking off, if any GUI is opened before the planet selection screen or in the planet selection screen, it will be impossible to select a planet to launch to
